name: Auto Committer Bot

on:
  schedule:
    - cron: '0 4-18/2 * * *' 
  workflow_dispatch: # Actions panelindən manual başlatmaq üçün

permissions:
  contents: write # Botun repozitoriyaya commit edə bilməsi üçün icazə

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_GIT_TOKEN }}
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Configure Git
        run: |
          git config --global user.name "TuranHuseynov0"
          git config --global user.email "turanhuseynov006@gmail.com"

      - name: Run Auto-Commit Script
        env:
          MY_GIT_TOKEN: ${{ secrets.MY_GIT_TOKEN }}
        run: python -u bot.py
